/**
 * Export graph structure as SQL statements for remote D1 import.
 * Content (problems, examples) now lives in R2 — this only exports graph structure.
 *
 * Handles all disciplines, cross-discipline edges, and collections.
 * Outputs batched SQL files to avoid D1's 10MB execution limit.
 *
 * Usage:
 *   npx tsx tools/export-sql.ts                    # Output SQL to stdout
 *   npx tsx tools/export-sql.ts --dir /tmp/deploy  # Output batched SQL files to directory
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "fs";
import { join } from "path";
import { getContentDir } from "./content-dir.js";

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

// Known discipline metadata (matches import-content.ts)
const DISCIPLINE_META: Record<string, { name: string; description: string; progressionModel: string }> = {
  math: { name: "Mathematics", description: "Mathematics from counting through algebra and statistics", progressionModel: "mastery-gated" },
  ela: { name: "English Language Arts", description: "Reading, writing, grammar, and vocabulary", progressionModel: "mastery-gated" },
  history: { name: "History", description: "Historical events, causes, and analysis", progressionModel: "context-layered" },
};

function main() {
  const args = process.argv.slice(2);
  const dirIdx = args.indexOf("--dir");
  const outputDir = dirIdx >= 0 ? args[dirIdx + 1] : null;

  const contentRoot = getContentDir();
  const disciplineDirs = readdirSync(contentRoot)
    .filter((d) => existsSync(join(contentRoot, d, "graph.json")))
    .sort();

  if (disciplineDirs.length === 0) {
    console.error("No disciplines found in content directory");
    process.exit(1);
  }

  const now = new Date().toISOString();
  const lines: string[] = [];

  lines.push(`-- Auto-generated by export-sql.ts on ${now}`);
  lines.push(`-- Disciplines: ${disciplineDirs.join(", ")}`);
  lines.push("");

  // Phase 1: Clear and insert disciplines, topics, content
  for (const dir of disciplineDirs) {
    const graph = JSON.parse(readFileSync(join(contentRoot, dir, "graph.json"), "utf-8"));
    const disciplineId = graph.disciplineId ?? dir;
    const meta = DISCIPLINE_META[disciplineId] ?? { name: graph.name, description: graph.description ?? "", progressionModel: "mastery-gated" };

    lines.push(`-- ═══ ${meta.name} (${disciplineId}) ═══`);
    lines.push("");

    // Clear discipline data (FK-safe order, matches import-content.ts clearDiscipline)
    lines.push(`DELETE FROM collection_topics WHERE collection_id IN (SELECT id FROM collections WHERE primary_discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM collections WHERE primary_discipline_id = '${disciplineId}';`);
    lines.push(`DELETE FROM group_session_participants WHERE group_session_id IN (SELECT id FROM group_sessions WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}'));`);
    lines.push(`DELETE FROM group_sessions WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM diagnostic_sessions WHERE discipline_id = '${disciplineId}';`);
    lines.push(`DELETE FROM assignment_responses WHERE assignment_id IN (SELECT id FROM assignments WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}'));`);
    lines.push(`DELETE FROM assignments WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM teach_sessions WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM review_log WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM user_topic_state WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM topic_content_versions WHERE topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM encompassings WHERE parent_topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM encompassings WHERE child_topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM prerequisites WHERE from_topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM prerequisites WHERE to_topic_id IN (SELECT id FROM topics WHERE discipline_id = '${disciplineId}');`);
    lines.push(`DELETE FROM topics WHERE discipline_id = '${disciplineId}';`);
    lines.push("");

    // Upsert discipline
    lines.push(`INSERT INTO disciplines (id, name, description, progression_model, created_at) VALUES ('${esc(disciplineId)}', '${esc(meta.name)}', '${esc(meta.description)}', '${esc(meta.progressionModel)}', '${now}') ON CONFLICT(id) DO UPDATE SET name = excluded.name, description = excluded.description, progression_model = excluded.progression_model;`);
    lines.push("");

    // Compute depths via topological sort (same logic as import-content.ts)
    const topicIds = new Set<string>(graph.topics.map((t: any) => t.id));
    const adjacency = new Map<string, string[]>();
    const inDegree = new Map<string, number>();
    for (const id of topicIds) {
      adjacency.set(id, []);
      inDegree.set(id, 0);
    }
    for (const p of graph.prerequisites) {
      if (p.from.includes(":")) continue; // skip cross-discipline
      if (topicIds.has(p.from) && topicIds.has(p.to)) {
        adjacency.get(p.from)!.push(p.to);
        inDegree.set(p.to, (inDegree.get(p.to) ?? 0) + 1);
      }
    }
    const queue: string[] = [];
    for (const [id, deg] of inDegree) {
      if (deg === 0) queue.push(id);
    }
    const depths = new Map<string, number>();
    for (const id of topicIds) depths.set(id, 0);
    while (queue.length > 0) {
      const node = queue.shift()!;
      const nodeDepth = depths.get(node) ?? 0;
      for (const child of adjacency.get(node) ?? []) {
        depths.set(child, Math.max(depths.get(child) ?? 0, nodeDepth + 1));
        const newDeg = (inDegree.get(child) ?? 1) - 1;
        inDegree.set(child, newDeg);
        if (newDeg === 0) queue.push(child);
      }
    }

    // Insert topics
    lines.push(`-- Topics (${graph.topics.length})`);
    for (const t of graph.topics) {
      const depth = depths.get(t.id) ?? 0;
      lines.push(
        `INSERT INTO topics (id, discipline_id, name, description, depth, grade_level, strand, standard_code, created_at) VALUES ('${esc(t.id)}', '${esc(disciplineId)}', '${esc(t.name)}', '${esc(t.description)}', ${depth}, ${t.gradeLevel}, ${t.strand ? `'${esc(t.strand)}'` : "NULL"}, ${t.standardCode ? `'${esc(t.standardCode)}'` : "NULL"}, '${now}');`
      );
    }
    lines.push("");

    // Insert collections
    if (graph.collections && graph.collections.length > 0) {
      lines.push(`-- Collections (${graph.collections.length})`);
      for (let i = 0; i < graph.collections.length; i++) {
        const c = graph.collections[i];
        lines.push(
          `INSERT INTO collections (id, primary_discipline_id, name, description, kind, grade_range, display_order, visibility, created_at) VALUES ('${esc(c.id)}', '${esc(disciplineId)}', '${esc(c.name)}', '${esc(c.description ?? "")}', '${esc(c.kind ?? "grade-band")}', ${c.gradeRange ? `'${esc(c.gradeRange)}'` : "NULL"}, ${i}, 'published', '${now}');`
        );
        for (let j = 0; j < (c.topicIds ?? []).length; j++) {
          lines.push(
            `INSERT INTO collection_topics (collection_id, topic_id, sort_order) VALUES ('${esc(c.id)}', '${esc(c.topicIds[j])}', ${j});`
          );
        }
      }
      lines.push("");
    }

    console.error(`${disciplineId}: ${graph.topics.length} topics (content now in R2)`);
  }

  // Phase 2: Insert prerequisites and encompassings for all disciplines
  // (all topics now exist in the output)
  lines.push(`-- ═══ Prerequisites & Encompassings ═══`);
  lines.push("");

  for (const dir of disciplineDirs) {
    const graph = JSON.parse(readFileSync(join(contentRoot, dir, "graph.json"), "utf-8"));

    lines.push(`-- Prerequisites: ${graph.name ?? dir}`);
    for (const p of graph.prerequisites) {
      if (p.from.includes(":")) continue; // stale inline cross-discipline edges
      lines.push(
        `INSERT INTO prerequisites (from_topic_id, to_topic_id, strength, type) VALUES ('${esc(p.from)}', '${esc(p.to)}', ${p.strength}, '${esc(p.type ?? "required")}');`
      );
    }
    lines.push("");

    if (graph.encompassings && graph.encompassings.length > 0) {
      lines.push(`-- Encompassings: ${graph.name ?? dir}`);
      for (const e of graph.encompassings) {
        lines.push(
          `INSERT INTO encompassings (parent_topic_id, child_topic_id, weight) VALUES ('${esc(e.parent)}', '${esc(e.child)}', ${e.weight});`
        );
      }
      lines.push("");
    }
  }

  // Phase 3: Cross-discipline edges
  const crossEdgePath = join(contentRoot, "cross-discipline-edges.json");
  if (existsSync(crossEdgePath)) {
    const crossFile = JSON.parse(readFileSync(crossEdgePath, "utf-8"));
    const crossEdges = crossFile.edges ?? [];
    if (crossEdges.length > 0) {
      lines.push(`-- Cross-discipline edges (${crossEdges.length})`);
      for (const edge of crossEdges) {
        const fromId = edge.from.split(":", 2)[1];
        const toId = edge.to.split(":", 2)[1];
        lines.push(
          `INSERT INTO prerequisites (from_topic_id, to_topic_id, strength, type) VALUES ('${esc(fromId)}', '${esc(toId)}', ${edge.strength}, '${esc(edge.type ?? "required")}');`
        );
      }
      lines.push("");
      console.error(`cross-discipline: ${crossEdges.length} edges`);
    }
  }

  // Output
  const sql = lines.join("\n");

  if (outputDir) {
    // Batched output for large content sets
    mkdirSync(outputDir, { recursive: true });
    const stmts = sql.split("\n").filter((l) => l.trim() && !l.startsWith("--"));
    const BATCH_SIZE = 500;
    const batches = Math.ceil(stmts.length / BATCH_SIZE);
    for (let i = 0; i < batches; i++) {
      const batch = stmts.slice(i * BATCH_SIZE, (i + 1) * BATCH_SIZE);
      const filename = `content-${String(i + 1).padStart(3, "0")}.sql`;
      writeFileSync(join(outputDir, filename), batch.join("\n") + "\n");
    }
    console.error(`\nWrote ${batches} batch files to ${outputDir} (${stmts.length} statements total)`);
    console.error(`Apply with: for f in ${outputDir}/content-*.sql; do npx wrangler d1 execute learn-db --remote --file="$f" --env production; done`);
  } else {
    console.log(sql);
    console.error(`\nTotal: ${lines.filter((l) => l.trim() && !l.startsWith("--")).length} SQL statements`);
  }
}

main();
