/**
 * Export content/ JSON files as SQL statements for remote D1 import.
 * Usage: npx tsx tools/export-sql.ts > content-import.sql
 * Then:  wrangler d1 execute learn-db --remote --file=content-import.sql --env production
 */
import { readFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

type GraphDefinition = {
  subjectId: string;
  subjectName: string;
  description?: string;
  gradeRange?: string;
  topics: {
    id: string;
    name: string;
    description: string;
    gradeLevel: number;
    standardCode: string | null;
  }[];
  prerequisites: { from: string; to: string; strength: number }[];
  encompassings?: { parent: string; child: string; weight: number }[];
};

type Problem = {
  id: string;
  topicId: string;
  difficulty: string;
  question: string;
  answer: string;
  hints: string[];
  solution: string;
};

type WorkedExample = {
  id: string;
  topicId: string;
  title: string;
  steps: { subgoalLabel: string; instruction: string; work: string; explanation: string }[];
};

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function main() {
  const contentDir = join(process.cwd(), "content", "math-foundations");
  const graphPath = join(contentDir, "graph.json");

  if (!existsSync(graphPath)) {
    console.error(`graph.json not found at ${graphPath}`);
    process.exit(1);
  }

  const graph: GraphDefinition = JSON.parse(readFileSync(graphPath, "utf-8"));

  // Load problems
  const problemsDir = join(contentDir, "problems");
  const problems = new Map<string, Problem[]>();
  if (existsSync(problemsDir)) {
    for (const file of readdirSync(problemsDir).filter((f) => f.endsWith(".json"))) {
      const topicProblems: Problem[] = JSON.parse(readFileSync(join(problemsDir, file), "utf-8"));
      for (const p of topicProblems) {
        const list = problems.get(p.topicId) ?? [];
        list.push(p);
        problems.set(p.topicId, list);
      }
    }
  }

  // Load examples
  const examplesDir = join(contentDir, "examples");
  const examples = new Map<string, WorkedExample[]>();
  if (existsSync(examplesDir)) {
    for (const file of readdirSync(examplesDir).filter((f) => f.endsWith(".json"))) {
      const topicExamples: WorkedExample[] = JSON.parse(readFileSync(join(examplesDir, file), "utf-8"));
      for (const e of topicExamples) {
        const list = examples.get(e.topicId) ?? [];
        list.push(e);
        examples.set(e.topicId, list);
      }
    }
  }

  const now = new Date().toISOString();
  const lines: string[] = [];

  // Clear existing data (FK-safe order)
  lines.push(`-- Auto-generated by export-sql.ts on ${now}`);
  lines.push(`DELETE FROM review_log WHERE topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM user_topic_state WHERE topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM assessment_content WHERE topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM instructional_content WHERE topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM encompassings WHERE parent_topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM encompassings WHERE child_topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM prerequisites WHERE from_topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM prerequisites WHERE to_topic_id IN (SELECT id FROM topics WHERE subject_id = '${graph.subjectId}');`);
  lines.push(`DELETE FROM topics WHERE subject_id = '${graph.subjectId}';`);
  lines.push(`DELETE FROM subjects WHERE id = '${graph.subjectId}';`);
  lines.push("");

  // Insert subject
  lines.push(
    `INSERT INTO subjects (id, name, description, grade_range, topic_count, created_at) VALUES ('${esc(graph.subjectId)}', '${esc(graph.subjectName)}', '${esc(graph.description ?? "")}', '${esc(graph.gradeRange ?? "K-5")}', ${graph.topics.length}, '${now}');`
  );
  lines.push("");

  // Compute depths via topological sort
  const topicIds = new Set(graph.topics.map((t) => t.id));
  const adjacency = new Map<string, string[]>();
  const inDegree = new Map<string, number>();
  for (const id of topicIds) {
    inDegree.set(id, 0);
    adjacency.set(id, []);
  }
  for (const p of graph.prerequisites) {
    adjacency.get(p.from)!.push(p.to);
    inDegree.set(p.to, (inDegree.get(p.to) ?? 0) + 1);
  }
  const queue: string[] = [];
  for (const [id, deg] of inDegree) {
    if (deg === 0) queue.push(id);
  }
  const depths = new Map<string, number>();
  for (const id of topicIds) depths.set(id, 0);
  while (queue.length > 0) {
    const node = queue.shift()!;
    const nodeDepth = depths.get(node) ?? 0;
    for (const child of adjacency.get(node) ?? []) {
      depths.set(child, Math.max(depths.get(child) ?? 0, nodeDepth + 1));
      const newDeg = (inDegree.get(child) ?? 1) - 1;
      inDegree.set(child, newDeg);
      if (newDeg === 0) queue.push(child);
    }
  }

  // Insert topics (graph nodes only)
  for (const t of graph.topics) {
    const depth = depths.get(t.id) ?? 0;
    lines.push(
      `INSERT INTO topics (id, subject_id, name, description, depth, grade_level, standard_code, created_at) VALUES ('${esc(t.id)}', '${esc(graph.subjectId)}', '${esc(t.name)}', '${esc(t.description)}', ${depth}, ${t.gradeLevel}, ${t.standardCode ? `'${esc(t.standardCode)}'` : "NULL"}, '${now}');`
    );
  }
  lines.push("");

  // Insert instructional content (worked examples)
  for (const [, topicExamples] of examples) {
    for (const e of topicExamples) {
      lines.push(
        `INSERT INTO instructional_content (id, topic_id, flavor, locale, presentation, version, title, steps_json, created_at, updated_at) VALUES ('${esc(e.id)}', '${esc(e.topicId)}', 'classic', 'en', 'individual', 1, '${esc(e.title)}', '${esc(JSON.stringify(e.steps))}', '${now}', '${now}');`
      );
    }
  }
  lines.push("");

  // Insert assessment content (problems)
  for (const [, topicProblems] of problems) {
    for (const p of topicProblems) {
      lines.push(
        `INSERT INTO assessment_content (id, topic_id, flavor, locale, presentation, version, type, difficulty, question, answer, hints_json, solution, created_at) VALUES ('${esc(p.id)}', '${esc(p.topicId)}', 'classic', 'en', 'individual', 1, 'text-qa', '${esc(p.difficulty)}', '${esc(p.question)}', '${esc(p.answer)}', '${esc(JSON.stringify(p.hints))}', '${esc(p.solution)}', '${now}');`
      );
    }
  }
  lines.push("");

  // Insert prerequisites
  for (const p of graph.prerequisites) {
    lines.push(
      `INSERT INTO prerequisites (from_topic_id, to_topic_id, strength) VALUES ('${esc(p.from)}', '${esc(p.to)}', ${p.strength});`
    );
  }
  lines.push("");

  // Insert encompassings
  if (graph.encompassings) {
    for (const e of graph.encompassings) {
      lines.push(
        `INSERT INTO encompassings (parent_topic_id, child_topic_id, weight) VALUES ('${esc(e.parent)}', '${esc(e.child)}', ${e.weight});`
      );
    }
  }

  console.log(lines.join("\n"));
}

main();
